blank_issues_enabled: false
contact_links:
- name: 💬 General questions or support
  url: https://github.com/diego81b/Thothix/discussions
  about: Use Discussions for questions, ideas, or clarifications.
