services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: thothix/postgres:17.5-thothix1.0
    container_name: thothix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@Admin123'
      POSTGRES_DB: thothix-db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thothix-db"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Applicazione Go
  thothix-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: thothix/api:1.0.0
    container_name: thothix-api
    restart: unless-stopped
    ports:
      - '30000:30000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=@Admin123
      - DB_NAME=thothix-db
      - PORT=30000
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
