name: Sync main to dev

on:
  push:
    branches:
    - main

jobs:
  sync-main-to-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Create PR from main to dev
      uses: repo-sync/pull-request@v2
      with:
        source_branch: 'main'
        destination_branch: 'dev'
        pr_title: 'chore: Sync main to dev'
        pr_body: 'Automated PR to keep dev up to date with main after release.'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        assignees: "diego81b"
